# Generated by Django 4.1.1 on 2024-06-23 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Areainversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese Area de inversion (ej.: Agricultura, Ganaderia,..)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese nombre de la Comunidad aborigen ', max_length=360)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese Localidad (ej..)', max_length=200)),
                ('departamento', models.CharField(help_text='Ingrese departamento)', max_length=100)),
                ('latitud', models.CharField(help_text='Ingrese Latitud', max_length=15)),
                ('longitud', models.CharField(help_text='Ingrese Longitud (ej..)', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese organismo', max_length=360)),
                ('dependencia', models.CharField(help_text='Ingrese Dependencia de este Organismo', max_length=360)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingrese nombre del responsable del Proyecto', max_length=240)),
                ('organismo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyecto.organismo')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField(help_text='Ingrese una breve descripcion del proyecto', max_length=1000)),
                ('beneficiarios', models.IntegerField()),
                ('montoinversion', models.IntegerField()),
                ('anioejecucion', models.IntegerField()),
                ('estado', models.CharField(blank=True, choices=[('n', 'No iniciado'), ('e', 'En ejecucion'), ('t', 'Terminado'), ('p', 'Paralizado')], default='e', help_text='Estado del proyecto', max_length=1)),
                ('observacion', models.TextField(help_text='Ingrese una breve aclaracion', max_length=1000)),
                ('areainversion', models.ManyToManyField(help_text='Seleccione el area de inversion para este proyecto', to='proyecto.areainversion')),
                ('comunidad', models.ManyToManyField(help_text='Select a Comunidad aborigen para este proyecto', to='proyecto.comunidad')),
                ('localidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyecto.localidad')),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyecto.responsable')),
            ],
            options={
                'ordering': ['responsable'],
            },
        ),
        migrations.CreateModel(
            name='Actualizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=1000)),
                ('fecha_actualizacion', models.DateField(blank=True, null=True)),
                ('fecha_validez', models.DateField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='proyecto.proyecto')),
                ('registrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_actualizacion'],
            },
        ),
    ]
